return {
  "nvim-treesitter/nvim-treesitter",
  -- commit = "f2778bd1a28b74adf5b1aa51aa57da85adfa3d16",
  opts = {
    ensure_installed = {
      "hyprlang",
      "tmux",
      "dart",
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
